"""Add independent read-only market scanner history and optional webhook events."""

from alembic import op
import sqlalchemy as sa

revision = "20260923_0004_scanner"
down_revision = "20260406_0003_price_alerts"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scanner_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("universe_size", sa.Integer(), nullable=False),
        sa.Column("analyzed", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("high_confluence", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scanner_runs_started_at"), "scanner_runs", ["started_at"], unique=False
    )
    op.create_table(
        "tradingview_events",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scanner_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candle_closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("long_score", sa.Integer(), nullable=False),
        sa.Column("short_score", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scanner_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scanner_snapshot_symbol_created",
        "scanner_snapshots",
        ["symbol", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scanner_snapshots_run_id"),
        "scanner_snapshots",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "market_setups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=5), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("readiness", sa.String(length=32), nullable=False),
        sa.Column("lifecycle", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column(
            "initial_invalidation", sa.Numeric(precision=30, scale=12), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notified_data", sa.JSON(), nullable=False),
        sa.Column("delivery_error", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["scanner_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_market_setup_symbol_direction",
        "market_setups",
        ["symbol", "direction", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_setups_lifecycle"), "market_setups", ["lifecycle"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_setups_lifecycle"), table_name="market_setups")
    op.drop_index("ix_market_setup_symbol_direction", table_name="market_setups")
    op.drop_table("market_setups")
    op.drop_index(op.f("ix_scanner_snapshots_run_id"), table_name="scanner_snapshots")
    op.drop_index("ix_scanner_snapshot_symbol_created", table_name="scanner_snapshots")
    op.drop_table("scanner_snapshots")
    op.drop_table("tradingview_events")
    op.drop_index(op.f("ix_scanner_runs_started_at"), table_name="scanner_runs")
    op.drop_table("scanner_runs")
    # ### end Alembic commands ###
