"""News context tables: append-only research context, never part of the trading score.

Revision ID: 20260924_0008_news
Revises: 20260924_0007_oi_snapshots
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20260924_0008_news"
down_revision = "20260924_0007_oi_snapshots"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_event_clusters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column("canonical_item_id", sa.String(length=160), nullable=False),
        sa.Column("canonical_url", sa.String(length=500), nullable=True),
        sa.Column("first_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_event_clusters_first_received_at"),
        "news_event_clusters",
        ["first_received_at"],
        unique=False,
    )
    op.create_table(
        "news_cluster_status",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("verification", sa.String(length=32), nullable=False),
        sa.Column("importance_score", sa.Integer(), nullable=False),
        sa.Column("importance_level", sa.String(length=10), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_event_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_cluster_status_cluster_id"),
        "news_cluster_status",
        ["cluster_id"],
        unique=False,
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_item_id", sa.String(length=120), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("source_type", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column("event_type_hint", sa.String(length=40), nullable=True),
        sa.Column("raw_payload_hash", sa.String(length=64), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=True),
        sa.Column("stages", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_event_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_item_id", name="uq_news_provider_item"
        ),
    )
    op.create_index(
        op.f("ix_news_items_cluster_id"), "news_items", ["cluster_id"], unique=False
    )
    op.create_index(
        "ix_news_items_payload_hash", "news_items", ["raw_payload_hash"], unique=False
    )
    op.create_index(
        "ix_news_items_received_at", "news_items", ["received_at"], unique=False
    )
    op.create_table(
        "news_classifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("news_item_id", sa.String(length=160), nullable=False),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("rule", sa.String(length=60), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("noise", sa.Boolean(), nullable=False),
        sa.Column("noise_reason", sa.String(length=40), nullable=True),
        sa.Column("importance_score", sa.Integer(), nullable=False),
        sa.Column("importance_level", sa.String(length=10), nullable=False),
        sa.Column("factors", sa.JSON(), nullable=False),
        sa.Column("verification", sa.String(length=32), nullable=False),
        sa.Column("freshness", sa.String(length=16), nullable=False),
        sa.Column("coverage", sa.JSON(), nullable=False),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_item_id"],
            ["news_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "news_item_id", "rule_version", name="uq_news_class_version"
        ),
    )
    op.create_index(
        op.f("ix_news_classifications_news_item_id"),
        "news_classifications",
        ["news_item_id"],
        unique=False,
    )
    op.create_table(
        "news_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("news_item_id", sa.String(length=160), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("match_type", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("matched_text", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_item_id"],
            ["news_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_entities_news_item_id"),
        "news_entities",
        ["news_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_entities_symbol"), "news_entities", ["symbol"], unique=False
    )
    op.create_table(
        "news_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("market_setup_id", sa.Uuid(), nullable=True),
        sa.Column("symbol", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=120), nullable=True),
        sa.Column("latency_ms", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_event_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_setup_id"],
            ["market_setups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        op.f("ix_news_alerts_cluster_id"), "news_alerts", ["cluster_id"], unique=False
    )
    op.create_index(
        op.f("ix_news_alerts_symbol"), "news_alerts", ["symbol"], unique=False
    )
    op.create_table(
        "news_setup_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("market_setup_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=40), nullable=False),
        sa.Column("match_type", sa.String(length=20), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("setup_score_at_link", sa.Integer(), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["news_event_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_setup_id"],
            ["market_setups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_id", "market_setup_id", name="uq_news_setup_link"),
    )
    op.create_index(
        op.f("ix_news_setup_links_cluster_id"),
        "news_setup_links",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_setup_links_market_setup_id"),
        "news_setup_links",
        ["market_setup_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_news_setup_links_market_setup_id"), table_name="news_setup_links"
    )
    op.drop_index(op.f("ix_news_setup_links_cluster_id"), table_name="news_setup_links")
    op.drop_table("news_setup_links")
    op.drop_index(op.f("ix_news_alerts_symbol"), table_name="news_alerts")
    op.drop_index(op.f("ix_news_alerts_cluster_id"), table_name="news_alerts")
    op.drop_table("news_alerts")
    op.drop_index(op.f("ix_news_entities_symbol"), table_name="news_entities")
    op.drop_index(op.f("ix_news_entities_news_item_id"), table_name="news_entities")
    op.drop_table("news_entities")
    op.drop_index(
        op.f("ix_news_classifications_news_item_id"), table_name="news_classifications"
    )
    op.drop_table("news_classifications")
    op.drop_index("ix_news_items_received_at", table_name="news_items")
    op.drop_index("ix_news_items_payload_hash", table_name="news_items")
    op.drop_index(op.f("ix_news_items_cluster_id"), table_name="news_items")
    op.drop_table("news_items")
    op.drop_index(
        op.f("ix_news_cluster_status_cluster_id"), table_name="news_cluster_status"
    )
    op.drop_table("news_cluster_status")
    op.drop_index(
        op.f("ix_news_event_clusters_first_received_at"),
        table_name="news_event_clusters",
    )
    op.drop_table("news_event_clusters")
    # ### end Alembic commands ###
